//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastAndEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Student { get; set; }
        public string Present { get; set; }
        public string Reasonable { get; set; }
    
        public virtual Student Student1 { get; set; }
    }
}
